# 
# 
#  .oooooo..o             o8o      .                         
# d8P'    `Y8             `"'    .o8                         
# Y88bo.      oo.ooooo.  oooo  .o888oo  .ooooo.  oooo d8b    
#  `"Y8888o.   888' `88b `888    888   d88' `88b `888""8P    
#      `"Y88b  888   888  888    888   888ooo888  888        
# oo     .d8P  888   888  888    888 . 888    .o  888        
# 8""88888P'   888bod8P' o888o   "888" `Y8bod8P' d888b       
#              888                                           
#             o888o                                          
# 
#       .o.                       .    o8o    .oooooo.   oooo                                .   
#      .888.                    .o8    `"'   d8P'  `Y8b  `888                              .o8   
#     .8"888.     ooo. .oo.   .o888oo oooo  888           888 .oo.    .ooooo.   .oooo.   .o888oo 
#    .8' `888.    `888P"Y88b    888   `888  888           888P"Y88b  d88' `88b `P  )88b    888   
#   .88ooo8888.    888   888    888    888  888           888   888  888ooo888  .oP"888    888   
#  .8'     `888.   888   888    888 .  888  `88b    ooo   888   888  888    .o d8(  888    888 . 
# o88o     o8888o o888o o888o   "888" o888o  `Y8bood8P'  o888o o888o `Y8bod8P' `Y888""8o   "888" 
# 
# Spiter AntiCheat configuration
# Documentation: https://docs.spiter.cc/
# KOOK: https://kook.top/fyLlw2
# QQ Group: 759357642
# 
# Thanks for using Spiter Anticheat!  |  Regotly
#
#
Setting:
  #
  #开启BC通信的功能
  #Enable BC communications
  #
  Bungeemode: false
  #Spiter不发送任何的Trs和Keepalive包（会导致所有延迟检测工作不正常）
  #Spiter does not send any Trs and Keepalive packets 
  #(which causes all delay detection to work improperly)
  #
  NotSendPacket:
    Trs-C0f: false
  #
  #是否启用spiter.bypass
  #Whether or not to enable spiter.bypass
  #
  Check-bypass: false
  Alerts:
  #
  # Whether to turn on experimental detection
  #Whether not to send alerts when the server is stuck (to minimize false positives due to server stuckness)
  #Whether to enable experimental detection
  #Whether to refresh when vl is full.
  #
    Experimental-VL-Add: true
    not-alerts-inLag: true
    Allow-Developmental: true
    join-on: true
    Reset-VL-On-Max: true
    CoolDown: 5.0
    JoinBypass: 5000
    vlreset-time (s): 450
    #生存模式检测
    Survival-check: true
    #创造模式检测
    Creating-check: false
    #旁观者模式检测
    Bystander-detection: false
    Command: /tp %player%
    Debug-Color: '&7'
    Experimental: '&aΔ'
    Developmental: '&c⚠'
    ConnectionHigh: '&4⥱'
    Display:
      FirstBar: '&8['
      LastBar: '&8]'
      FillBar: '&c|'
      EmptyBar: '&7|'
  Punishment:
    Message:
      Enabled: false
      #是否启用全局模式下的封禁系统
    AllCheck:
      Enabled: false
      Commands:
      - kick %player% &7[&bSpiter&7] &CUnfair Advantage
  ForceBan:
  #forceban指令执行什么命令
    Commands:
    - kick %player% &7[&bSpiter&7] &CUnfair Advantage
Check:
  Reach:
  # 检测强度，最高为1，最低为4，最高越强，但是误报++
    Level-(1,2,3,4): 3
# 限制和阻止作弊者利用延迟扩大攻击范围的安全措施
# 通过连接暂停或延迟，人为地拉近目标距离
# 以获得战斗优势。
# 建议默认启用此功能。
  blink:
    prevention_tolerance_cancel: true
#运行Spiter阻止战斗作弊者，让可能正常的玩家获得优势
  combat:
    prevention_tolerance_reducedamage: true
  autoblock:
    cancel:
      Illegal_Block: true
      highversion_autoblock: false
  #cps限制检测
  # 每秒允许玩家点击多少次。
  # 建议保持在 30 次以下，以防滥用。
  cps:
    # It is recommended to keep this below 26 to prevent abuse.
    left_limit: 25
    # It is recommended to keep this below 30 to prevent abuse.
    right_limit: 40
  Heuristic:
    A:
      Fastcheck: false
    C:
      Fastcheck: false
  Packetevent:
  #让packetevent的优先级降为最低 （抢intave的发包）
    LevelLow: false
  trs:
    polarsend: false
  Cancel:
    AttackLevel: 0.6
    move:
      morevel:
        magnification:
          x: 1.5
          y: 1.0
          z: 1.5
        custom:
          enable: false
          x: 0.45
          y: 0.3
          z: 0.45
  Ghostblockcheck:
    Enabled: true
    changeblock:
      Enabled: true
    Ghostblocksetback: true
  Phase:
    setback: true
  Bot:
    Enable: true
    Spawn:
      distance: 1.8
      heights: 3.0
      duration: 10
      invisible: true
  Brand:
    Enabled: true
    Command: /tp %player%
  Client:
    Detect-Vape: true
    Detect-Lite: true
    Blocker-Enabled: false
    Blocked-Brands:
    - CM-Pack
    - Blazing-Pack
    - Crystalware
    - Vivecraft
Database:
#MongoDB
  enable: false
  host: 127.0.0.1
  port: 27017
  database: database
  authentication:
    enable: false
    authname: Spiter
    password: Spiter
  Collection:
    Logs: logs
Command:
  Spiter:
    Help-Command-Customize-Enable: false
    Help-Command-Customize:
    - ''
    - '&e| &7/spiter gui &8| &fOpens GUI.'
    - '&e| &7/alerts &8| &fToggle alerts.'
    - '&e| &7/spiter alerts &8| &fToggle alerts.'
    - '&e| &7/spiter user (player) &8| &fInformation about the player.'
    - '&e| &7/spiter forceban (player) &8| &fPunishes the player.'
    - '&e| &7/spiter menu &8| &fOpens GUI.'
    - '&e| &7/spiter printlogs &8| &fShows the logs of a player.'
    - '&e| &7/spiter crash2 &8| &fCrashes the player.'
    - '&e| &7/spiter logs (player) &8| &fShows the logs of a player.'
    - '&e| &7/spiter reload &8| &fReloads configuration.'
    Name: Spiter
    commands:
    - spiter
    commandtabName: tab
    commandtab:
    - aac
    - grim
    - buzz
    - polar
    - karhu
    - intave
Spiter:
  Description: Securing fair play, one check at a time with Spiter AntiCheat
  Version: '3.1'
  Website: spiter.cc
  Authors:
  - Regotly
System:
  #是否堆积垃圾
  Alerts-Logs-In-Console: true
  #是否使用临时文件夹来存储logs信息 （用于单服务器机器所有子服的logs收集）
  Logs-Use-Temp-File: true
  #是否启用API
  API: true
  Haste-Server: paste.md-5.net
Freeze:
  message-enable: true
  player-quit-command:
    enable: true
    command:
    - 'kick %player% %prefix%&cInvalid client brand: &7%brand%'
OPTIONS:
  Processing:
    Better-Buffer: true
Message:
  Check:
    Brand:
      Message: '%prefix%&b%player% &7joined using &7[&e%brand%&7]&7.'
      Hover:
      - '&fIp: &b%ip%'
      - '&fVersion: &b%version%'
      - ' '
      - '&7Click to teleport to &b%player%'
    Client:
      Blocker-Command:
      - 'kick %player% %prefix%&cInvalid client brand: &7%brand%'
  Alerts:
    Layout: '%prefix% &7> &3%player% &8| &f%checkName%&7(&f%checkType%&7)&c%bar% &8|
      &3x%vl%  %tags%'
    Hover:
    - '&f%description%'
    - ''
    - '%debug%'
    - ''
    - '&7(&fPing: &7%ping%  &fTps: &a%tps% &f(V%version%) - &b[%client%] &7)'
    - '&a(Click to teleport)'
  Verbose: '&7[&bVerbose&7] &f%player% &7| &r&f%checkName% &f%checkType% &7| &f%buffer%%'
  PUNISHMENTS:
    Message:
    - '&7&m--------------------------------------------------'
    - '&c&l✗ &b&lSpiter Cheat Detection'
    - '&c&l✗ %prefix%&7has removed %player% &7from the network due to cheating.'
    - '&7&m--------------------------------------------------'
  BROADCAST:
    Message:
    - '&7&m--------------------------------------------------'
    - '&c&l✗ &b&lSpiter Cheat Detection'
    - '%prefix%&bSpiter &7has banned &b%bans% &7players in the last &b15 &7minutes.'
    - '&7&m--------------------------------------------------'
  Network-settings:
    kick-message: Unstable Connection
    transaction-delay: '&c%player% &7Unstable Connection (&eTrans&7).'
    cancel-keepalives-alert: '&c%player% &7Unstable Connection (&eKeepalive&7)'
    cancel-transactions-alert: '&c%player% &7Unstable Connection (&eTransaction&7)'
    own-keepalives-alert: '&c%player% &7Unstable Connection (&eKeepalive&7)'
    own-transactions-alert: '&c%player% &7Unstable Connection (&eTransaction&7)'
    cancel-and-own-kick-message: Unstable Connection
    wrong-spoof-kick-message: Unstable Connection
  server-lag-protection:
    warning-message: '%prefix% &cThe Server is Lag?'
    max-tick-length: 120
  freeze:
    getbanned-message: '%prefix% &c%player% &fBanned for being checked by Staff but
      quitting the game.'
    sendplayer-message: '&fPlease add Staff QQ xxxxxxxxx for checking - Exit the game
      will be banned!'
BROADCAST:
  Enabled: true
  Reset-Counter: true
  Spoof:
    Enabled: false
    Min: 5
    Max: 35
  Time: 18000
  Sound: NONE
Network-settings:
#无需开启，Pingspoof会检测
  enabled: false
  SpoofPacket: false
  DelayPacket: false
