# Spiter AntiCheat - Config
Setting:
  Bungeemode: false
  #可能增加cpu计算
  Bot:
    Spawn:
      distance: 1.8
      heights: 3.0
      duration: 10
      invisible: true
      
  NotSendPacket:
    Trs-C0f: false
    #可能增加网络io
  Check-bypass: false
  Ghostblockcheck:
    Enabled: true
    Ghostblocksetback: true
  Phase:
    setback: true
  Alerts:
    Experimental-VL-Add: true
    not-alerts-inLag: true
    #关闭可能增加误报
    Allow-Developmental: true
    join-on: true
    #加入开启alerts
    Reset-VL-On-Max: true
    #是否在vl满的时候清除
    CoolDown: 5.0
    JoinBypass: 5000
    vlreset-time (s): 300
    Survival-check: true
    #是否开启生存模式检查
    Creating-check: false
    #是否开启创造模式检查
    Bystander-detection: false
    #是否开启观察者模式检测
    Command: /tp %player%
    Debug-Color: '&7'
    Experimental: '&aΔ'
    Developmental: '&c⚠'
    ConnectionHigh: '&4⥱'
    Display:
      FirstBar: '&8['
      LastBar: '&8]'
      FillBar: '&c|'
      EmptyBar: '&7|'
  Punishment:
    Message:
      Enabled: false
    AllCheck:
      Enabled: false
      Commands:
      - kick %player% &7[&bSpiter&7] &CUnfair Advantage
  ForceBan:
    Commands:
    - kick %player% &7[&bSpiter&7] &CUnfair Advantage
CheckSetting:
  Reach:
    Level-(1,2,3,4): 3
Database:
  enable: false
  #暂时没有写好，不要开启
  host: 127.0.0.1
  port: 12345
  database: database
  authentication:
    enable: false
    authname: Spiter
    password: Spiter
  Collection:
    Logs: logs
Command:
  Spiter:
    Help-Command-Customize-Enable: false
    #是否启用自定义help描述
    Help-Command-Customize:
    - ''
    - '&e| &7/spiter gui &8| &fOpens GUI.'
    - '&e| &7/alerts &8| &fToggle alerts.'
    - '&e| &7/spiter alerts &8| &fToggle alerts.'
    - '&e| &7/spiter user (player) &8| &fInformation about the player.'
    - '&e| &7/spiter forceban (player) &8| &fPunishes the player.'
    - '&e| &7/spiter menu &8| &fOpens GUI.'
    - '&e| &7/spiter printlogs &8| &fShows the logs of a player.'
    - '&e| &7/spiter crash2 &8| &fCrashes the player.'
    - '&e| &7/spiter logs (player) &8| &fShows the logs of a player.'
    - '&e| &7/spiter reload &8| &fReloads configuration.'
    Name: Spiter
    #自定义名称
    commands:
    #自定义command
    - spiter
    commandtabName: tab
    commandtab:
    - aac
    - grim
    - buzz
    #假的命令tab
Spiter:
  Description: Securing fair play, one check at a time with Spiter AntiCheat
  Version: '3.1'
  Website: spiter.cc
  Authors:
  - Regotly
System:
  Alerts-Logs-In-Console: true
  #可能造成无意义的能耗
  Logs-Use-Temp-File: true
  #开启可以在同一机器上面看到同一玩家的logs信息
  API: false
  #是否启用API
  Haste-Server: paste.md-5.net
Freeze:
  message-enable: true
  #是否启用冻结命令
  player-quit-command:
    enable: true
    command:
    - 'kick %player% %prefix%&cInvalid client brand: &7%brand%'
OPTIONS:
  Processing:
  #不要动
    Better-Buffer: true
Check:
  Brand:
    Enabled: true
    #可能增加能耗
    Command: /tp %player%
  Client:
  #开启客户端检测
    Detect-Vape: true
    Detect-Lite: true
    Blocker-Enabled: false
    Blocked-Brands:
    - CM-Pack
    - Blazing-Pack
    - Crystalware
    - Vivecraft
Message:
  Check:
    Brand:
      Message: '%prefix%&b%player% &7joined using &7[&e%brand%&7]&7.'
      Hover:
      - '&fIp: &b%ip%'
      - '&fVersion: &b%version%'
      - ' '
      - '&7Click to teleport to &b%player%'
    Client:
      Blocker-Command:
      - 'kick %player% %prefix%&cInvalid client brand: &7%brand%'
  Alerts:
    Layout: '%prefix%&f%player% &7failed &f%checkName%&7(&f%checkType%&7) &c%bar%
      %tags%'
    Hover:
    - '&f%description%'
    - ''
    - '%debug%'
    - ''
    - '&7(&fPing: &7%ping%  &fTps: &a%tps% &f(V%version%)&7) &a(Click to teleport)'
  Verbose: '&7[&bVerbose&7] &f%player% &7| &r&f%checkName% &f%checkType% &7| &f%buffer%%'
  PUNISHMENTS:
    Message:
    - '&7&m--------------------------------------------------'
    - '&c&l✗ &b&lSpiter Cheat Detection'
    - '&c&l✗ %prefix%&7has removed %player% &7from the network due to cheating.'
    - '&7&m--------------------------------------------------'
  BROADCAST:
    Message:
    - '&7&m--------------------------------------------------'
    - '&c&l✗ &b&lSpiter Cheat Detection'
    - '%prefix%&bSpiter &7has banned &b%bans% &7players in the last &b15 &7minutes.'
    - '&7&m--------------------------------------------------'
  Network-settings:
    kick-message: 'java.net.IOException Connection timed out: no further information'
    transaction-delay: '&c%player% &7Skipped the trading package.'
    cancel-keepalives-alert: '&c%player% &7cancelled keepalive packets with total
      of &a%invalid% / %total%'
    cancel-transactions-alert: '&c%player% &7cancelled transaction packets with total
      of &a%invalid% / %total%'
    own-keepalives-alert: '&c%player% &7sent skip keepalives &7total of &a%invalid%
      / %total%'
    own-transactions-alert: '&c%player% &7sent skip transactions &7total of &a%invalid%
      / %total%'
    cancel-and-own-kick-message: 'java.net.IOException Connection timed out: no further
      information'
    wrong-spoof-kick-message: Timed out.
  server-lag-protection:
    warning-message: '%prefix% &cThe Server is Lag?'
    max-tick-length: 120
  freeze:
    getbanned-message: '%prefix% &c%player% &f被Staff查端但退出了游戏所以被封禁.'
    sendplayer-message: '&f请加StaffQQ xxxxxxx 进行查端 - 退出游戏将封禁'
BROADCAST:
  Enabled: true
  Reset-Counter: true
  Spoof:
    Enabled: false
    Min: 5
    Max: 35
  Time: 18000
  Sound: NONE
Network-settings:
#无需打开，Pingspoof检测
  enabled: false
  SpoofPacket: false
  DelayPacket: false
Option:
  Check:
    autoblockcancel: false
    #是否cancel无意义的ab，参考intave
    cancel-highversion-autoblock: false
    #是否cancel高版本ab，减少高版本ab绕过
